import { ColumnType } from 'antd/es/table';
import { divideBy1e18 } from '../../../../../../utils/number.utils';
import {
  renderAccountId,
  createTitleWithTooltipDescription,
  renderFormattedValue,
  renderFormattedRealValue,
  renderDate,
  formatTableDate,
} from '../../../../../../utils/table.utils';

type BaseSignal = {
  id: string;
  curator: {
    id: string;
  };
  currentGRTValue: string;
  signalledTokens: string;
  unsignalledTokens: string;
  PLGrt: string;
  realizedPLGrt: string;
  unrealizedPLGrt: string;
};

export type NameSignal = BaseSignal & {
  nameSignal: string;
  lastNameSignalChange: number;
};

export type Signal = BaseSignal & {
  signal: string;
  lastSignalChange: number;
};

export type SubgraphCuratorsRow = {
  id: string;
  key: string;
  curator: string;
  currentGRTValue: number;
  shares: number;
  signalledTokens: number;
  unsignalledTokens: number;
  PLGrt: number;
  realizedPLGrt: number;
  unrealizedPLGrt: number;
  lastChange: number;
  type: 'Auto-Migrate' | 'Deployment Signal';
};

const titles: Record<Exclude<keyof SubgraphCuratorsRow, 'id' | 'key'>, string> = {
  curator: 'Curator ID',
  type: 'Signal Type',
  currentGRTValue: 'Potential Signals Value',
  shares: 'Shares',
  signalledTokens: 'Signaled',
  unsignalledTokens: 'Unsignaled',
  PLGrt: 'P/L',
  realizedPLGrt: 'Realized P/L',
  unrealizedPLGrt: 'Unrealized P/L',
  lastChange: 'Last Activity',
};

export const columnsWidth = {
  '2560': [193, 210, 206, 206, 206, 206, 206, 206, 206, 220],
  '1920': [174, 182, 132, 132, 132, 132, 132, 132, 132, 202],
  '1440': [154, 162, 120, 120, 120, 120, 120, 120, 120, 180],
  '1280': [136, 140, 108, 108, 108, 108, 108, 108, 108, 152],
};

export const columns: Array<ColumnType<SubgraphCuratorsRow>> = [
  {
    title: createTitleWithTooltipDescription(titles.curator),
    dataIndex: 'curator',
    key: 'curator',
    align: 'center',
    render: renderAccountId('curator-details'),
  },
  {
    title: createTitleWithTooltipDescription(titles.type),
    dataIndex: 'type',
    key: 'type',
    align: 'center',
  },
  {
    title: createTitleWithTooltipDescription(
      titles.currentGRTValue,
      'Amount of GRT that can be received by Curator if unsignal from <strong>this</strong> subgraph.',
    ),
    dataIndex: 'currentGRTValue',
    key: 'currentGRTValue',
    render: renderFormattedValue,
  },
  {
    title: createTitleWithTooltipDescription(
      titles.shares,
      `
        Shares are minted by depositing ("signaling") GRT into a subgraph's bonding curve and entitle the 
        holder to a share of the Curator commision on future query fees generated by the subgraph.
      `,
    ),
    dataIndex: 'shares',
    key: 'shares',
    render: renderFormattedValue,
  },
  {
    title: createTitleWithTooltipDescription(
      titles.signalledTokens,
      'All-time amount of GRT spent on signaling to this subgraph.',
    ),
    dataIndex: 'signalledTokens',
    key: 'signalledTokens',
    render: renderFormattedValue,
  },
  {
    title: createTitleWithTooltipDescription(
      titles.unsignalledTokens,
      'All-time amount of GRT received from unsignaling from this subgraph.',
    ),
    dataIndex: 'unsignalledTokens',
    key: 'unsignalledTokens',
    render: renderFormattedValue,
  },
  {
    title: createTitleWithTooltipDescription(
      titles.PLGrt,
      'Unsignaled GRTs minus signaled GRT. Includes realized and unrealized P/L from this subgraph.',
    ),
    dataIndex: 'PLGrt',
    key: 'PLGrt',
    render: renderFormattedRealValue,
  },
  {
    title: createTitleWithTooltipDescription(
      titles.realizedPLGrt,
      'Received P/L from unsignaling from this subgraph.',
    ),
    dataIndex: 'realizedPLGrt',
    key: 'realizedPLGrt',
    render: renderFormattedValue,
  },
  {
    title: createTitleWithTooltipDescription(
      titles.unrealizedPLGrt,
      'Potential P/L from current signals from this subgraph.',
    ),
    dataIndex: 'unrealizedPLGrt',
    key: 'unrealizedPLGrt',
    render: renderFormattedValue,
  },
  {
    title: createTitleWithTooltipDescription(titles.lastChange),
    dataIndex: 'lastChange',
    key: 'lastChange',
    align: 'center',
    render: renderDate,
  },
];

type TypedNameSignal = {
  type: 'Auto-Migrate';
} & NameSignal;

type TypedSignal = {
  type: 'Deployment Signal';
} & Signal;

export const transformToRow = (typedSignal: TypedNameSignal | TypedSignal): SubgraphCuratorsRow => {
  const {
    id,
    curator: { id: curatorId },
    currentGRTValue,
    signalledTokens,
    unsignalledTokens,
    PLGrt,
    realizedPLGrt,
    unrealizedPLGrt,
    type,
  } = typedSignal;

  const baseSignal = {
    id,
    key: id,
    curator: curatorId,
    currentGRTValue: divideBy1e18(currentGRTValue),
    signalledTokens: divideBy1e18(signalledTokens),
    unsignalledTokens: divideBy1e18(unsignalledTokens),
    PLGrt: divideBy1e18(PLGrt),
    realizedPLGrt: divideBy1e18(realizedPLGrt),
    unrealizedPLGrt: divideBy1e18(unrealizedPLGrt),
    type,
  };

  return typedSignal.type === 'Auto-Migrate'
    ? {
        ...baseSignal,
        shares: divideBy1e18(typedSignal.nameSignal),
        lastChange: typedSignal.lastNameSignalChange,
      }
    : {
        ...baseSignal,
        shares: divideBy1e18(typedSignal.signal),
        lastChange: typedSignal.lastSignalChange,
      };
};

export const transformToCsvRow = ({
  curator,
  currentGRTValue,
  shares,
  signalledTokens,
  unsignalledTokens,
  PLGrt,
  realizedPLGrt,
  unrealizedPLGrt,
  lastChange,
  type,
}: SubgraphCuratorsRow) => ({
  [titles.curator]: type,
  [titles.type]: curator,
  [titles.currentGRTValue]: currentGRTValue,
  [titles.shares]: shares,
  [titles.signalledTokens]: signalledTokens,
  [titles.unsignalledTokens]: unsignalledTokens,
  [titles.PLGrt]: PLGrt,
  [titles.realizedPLGrt]: realizedPLGrt,
  [titles.unrealizedPLGrt]: unrealizedPLGrt,
  [titles.lastChange]: lastChange ? formatTableDate(lastChange) : null,
});
